[project]
name = "nbvim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arthur Albarelli", email = "arthuralbarelli@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "textual>=8.2.8",
]

[project.scripts]
nbvim = "nbvim:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
